apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock-api
  template:
    metadata:
      labels:
        app: stock-api
    spec:
      containers:
      - name: stock-api
        image: larrysang/stock-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: STOCK_MODELS_PATH
          value: "/app/models"
---
apiVersion: v1
kind: Service
metadata:
  name: stock-api-service
spec:
  type: LoadBalancer
  selector:
    app: stock-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
