global:
  scrape_interval: 300s  
scrape_configs:
  - job_name: 'stock-api'
    metrics_path: '/metrics'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: stock-api
