name: Docker Release
on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1, v2.0, etc.

env:
  REGISTRY: docker.io
  IMAGE_NAME: larrysang/stock-api

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }} 
          password: ${{ secrets.DOCKER_HUB_TOKEN }}    

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/api/Dockerfile.api
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}  
