name: Docker Release
on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1, v2.0, etc.

# Environment variables that can be reused across steps
env:
  REGISTRY: docker.io # Docker registry where the image will be pushed
  IMAGE_NAME: larrysang/stock-api # The name of the Docker image (namespace/repository)

jobs:
  build-and-push: # This job builds and pushes the Docker image
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu runner
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4 # Checks out the code from the repository so that the Dockerfile and project files are available

      - name: Login to Docker Hub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }} 
          password: ${{ secrets.DOCKER_HUB_TOKEN }}    

      - name: Build and push Docker image 
        uses: docker/build-push-action@v5  # Action to build and push the Docker image to Docker Hub
        with:
          context: .
          file: src/api/Dockerfile.api
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}  
